"""add review

Revision ID: 679550619397
Revises: 5acd6a3f97d6
Create Date: 2025-06-18 12:09:20.291861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679550619397'
down_revision = '5acd6a3f97d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customers', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'email')
    op.drop_table('reviews')
    # ### end Alembic commands ###
